port: 7879
env: dev
main_db:
  dsn: "root:p4ssw0rd@tcp(127.0.0.1:33061)/done_list?charset=utf8mb4&timeout=5s&readTimeout=5s&writeTimeout=5s&interpolateParams=true"
llm:
  open_ai_api_key: ""
  open_ai_model_name: "GPT-4o"
  embedding_model_name: "text-embedding-3-large"
  vector_db_host: ""
  redis_vector:
    scheme: "redis"
    host: "127.0.0.1:6379"
    index: "Document"